### ISSUE TITLE
IO_LAYOUT=0,0 causes FATAL "fms_io(get_field_size): The io domain must be defined"

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/icebergs#18]
If IO_LAYOUT in SIS2 is set to 0,0 we get:

> FATAL from PE   109: fms_io(get_field_size): The io domain must be defined

We often run with IO_LAYOUT=2,2 which seems to run fine.

**Comment by Hallberg-NOAA** [comment]
Changing MOM_domains to always use and IO_domain, even when IO_LAYOUT=0,0 in SIS_input corrects this problem. This issue was resolved with commit NOAA-GFDL/MOM6@51442eed32e9219f442663bc60289d14b714f87d.
