### ISSUE TITLE
model crashes when trying to restart from non-combined icebergs restart files

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/icebergs#20]
Here's what happens when I try to restart icebergs without combining the restart files ( experiment MOM6_GOLD_SIS2_bergs)

```
Rank 16 [Wed Dec 30 14:49:00 2015] [c0-0c0s1n2] Fatal error in MPI_Allreduce: Message truncated, error stack:
MPI_Allreduce(888)......................: MPI_Allreduce(sbuf=0x7ffffffe8dc4, rbuf=0x7ffffffe7e60, count=1, dtype=0x4c000430, MPI_MAX, comm=0x84000002) failed
MPIR_Allreduce_impl(739)................: 
MPIR_Allreduce_intra(223)...............: 
MPIR_Bcast_impl(1320)...................: 
MPIR_Bcast_intra(1154)..................: 
MPIR_Bcast_binomial(148)................: 
MPIDI_CH3_PktHandler_EagerShortSend(350): Message from rank 0 and tag 2 truncated; 8 bytes received but buffer size is 4
Internal Error: invalid error code 60e50e (Ring ids do not match) in MPIR_Allreduce_impl:739
Rank 32 [Wed Dec 30 14:49:00 2015] [c0-0c0s1n3] Fatal error in MPI_Allreduce: Other MPI error, error stack:
MPI_Allreduce(888)......: MPI_Allreduce(sbuf=0x7ffffffe8dc4, rbuf=0x7ffffffe7e60, count=1, dtype=0x4c000430, MPI_MAX, comm=0x84000004) failed
MPIR_Allreduce_impl(739): 
Rank 48 [Wed Dec 30 14:49:00 2015] [c0-0c0s1n3] Fatal error in MPI_Allreduce: Other MPI error, error stack:
MPI_Allreduce(888).......: MPI_Allreduce(sbuf=0x7ffffffe6530, rbuf=0x7ffffffe6320, count=1, dtype=0x4c000831, MPI_SUM, comm=0x84000002) failed
MPIR_Allreduce_impl(739).: 
MPIR_Allreduce_intra(223): 
MPIR_Bcast_impl(1320)....: 
MPIR_Bcast_intra(1154)...: 
MPIR_Bcast_binomial(157).: message sizes do not match across processes in the collective
forrtl: error (76): Abort trap signal
Image              PC                Routine            Line        Source             
fms_MOM6_SIS2_com  00000000060F7051  mpp_mod_mp_mpp_su          21  mpp_sum_mpi.h
fms_MOM6_SIS2_com  000000000611A34D  mpp_mod_mp_mpp_su          15  mpp_sum.inc
fms_MOM6_SIS2_com  00000000060FBA06  mpp_mod_mp_mpp_ch          16  mpp_chksum_int.h
fms_MOM6_SIS2_com  0000000006107BF0  mpp_mod_mp_mpp_ch          13  mpp_chksum.h
fms_MOM6_SIS2_com  0000000005E18EBB  mpp_io_mod_mp_mpp          85  mpp_read_compressed.h
fms_MOM6_SIS2_com  0000000004F1F7BE  fms_io_mod_mp_rea        5153  fms_io.F90
fms_MOM6_SIS2_com  0000000004F1DD04  fms_io_mod_mp_rea        5111  fms_io.F90
fms_MOM6_SIS2_com  0000000004DD9E0C  ice_bergs_io_mp_r         693  icebergs_io.F90
fms_MOM6_SIS2_com  0000000004BF7CFD  ice_bergs_mp_iceb         103  icebergs.F90
fms_MOM6_SIS2_com  0000000000981922  ice_model_mod_mp_        4085  ice_model.F90
fms_MOM6_SIS2_com  0000000000416B65  coupler_main_IP_c        1540  coupler_main.F90
fms_MOM6_SIS2_com  0000000000400B4B  MAIN__                    520  coupler_main.F90

other pes at:

fms_MOM6_SIS2_com  00000000060F47DE  mpp_mod_mp_mpp_ma          14  mpp_reduce_mpi.h
fms_MOM6_SIS2_com  0000000004DAE124  ice_bergs_framewo        2744  icebergs_framework.F90
fms_MOM6_SIS2_com  0000000004BF7D29  ice_bergs_mp_iceb         105  icebergs.F90
fms_MOM6_SIS2_com  0000000000981922  ice_model_mod_mp_        4085  ice_model.F90
fms_MOM6_SIS2_com  0000000000416B65  coupler_main_IP_c        1540  coupler_main.F90
fms_MOM6_SIS2_com  0000000000400B4B  MAIN__                    520  coupler_main.F90
```

I think the traceback is trying to say there is a race condition somewhere. 

When I comment out the line following line in  shared/mpp/include/mpp_read_compressed.h
so that the compute_chksum is false and the code doesn't go through the checksum routines the 
crash goes away!

if (ANY(field%checksum /= default_field%checksum) ) compute_chksum = .TRUE.

workdir: /lustre/f1/Niki.Zadeh/work/ulm_201510_mom6_2015.12.17/MOM6_GOLD_SIS2_bergs_2x0m1d_64pe.o1451489785

**Comment by nikizadehgfdl** [comment]
I think this is because the mpp_checksum is called only by a subset of Ice pes that have at least one iceberg in their corresponding io_tile, but the mpp_checksum is expecting and waiting for all Ice pes which is basically causing a hang.

**Comment by nikizadehgfdl** [comment]
The restart works fine when I set the io_layout to be "1,2" in which case both of the two distributed restarts have bergs in them.  
For io_layout=1,4  the issue arises because two of the restart files have no bergs in them and the if statement on line  659 of icebergs_io.F90 prohibits those pes to call  read_unlimited_axis which in turn calls an mpp_checksum.

**Comment by Zhi-Liang** [comment]
Use the following fix will solve the issue.
1) user/z1l/dev for icebergs.git
2) user/z1l/dev  http://gitlab.gfdl.noaa.gov/fms/shared.git

**Comment by nikizadehgfdl** [comment]
These updates cause a crash in the first leg of the experiment where there is no icebergs restarts at all:

FATAL from PE     7: fms_io_mod(read_compressed_2d): file INPUT/icebergs.res.nc(with the consideration of tile number) and corresponding distributed file are not found

stdout:
/lustre/f1/Niki.Zadeh/ulm_201510_mom6_2015.12.17/MOM6_GOLD_SIS2_bergs/ncrc3.intel15-prod/stdout/run/MOM6_GOLD_SIS2_bergs_2x0m1d_64pe.o39107

**Comment by Zhi-Liang** [comment]
Hi Niki,

   I just made a fix to the same branch. Please try again.

Zhi

**Comment by nikizadehgfdl** [comment]
The new updates worked. With these updates the test experiment could restart from distributed icebergs restart files properly. I'll handle the pull request for icebergs once I will have run a complete set of regressions.
