### ISSUE TITLE
icebergs cannot restart from distributed restart files

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/icebergs#47]
When we do not combine iceberg restart files at the end of the 1st day of  2x1day restart experiment the model crashes with 

```
FATAL from PE     0: diamonds, read_restart_bergs: Iceberg copied twice

forrtl: error (76): Abort trap signal
Image              PC                Routine            Line        Source
fms_MOM6_SIS2_com  0000000001FEF3E5  Unknown               Unknown  Unknown
fms_MOM6_SIS2_com  0000000001A54B06  mpp_mod_mp_mpp_er          50  mpp_util_mpi.inc
fms_MOM6_SIS2_com  00000000006B3E4D  ice_bergs_io_mp_r         875  icebergs_io.F90
fms_MOM6_SIS2_com  0000000000677586  ice_bergs_mp_iceb         116  icebergs.F90
fms_MOM6_SIS2_com  00000000004BE6DD  ice_model_mod_mp_        2316  ice_model.F90
fms_MOM6_SIS2_com  0000000000408FA5  coupler_main_IP_c        1574  coupler_main.F90
fms_MOM6_SIS2_com  0000000000401351  MAIN__                    525  coupler_main.F90
```

This used to work before (and after the new io was implemented by Jeff).

**Comment by nikizadehgfdl** [comment]
To reproduce this run a restart test for ice_ocean_SIS2/SIS2_icebergs with SIS_override including

#override IO_LAYOUT = 1,4
#override LAYOUT    = 16,8

**Comment by adcroft** [comment]
I can't even get that far with distributed restarts. I get a SEGV from
inside read_compressed_2d():

#1  0x27BBF60 in _gfortrani_backtrace_handler at compile_options.c:129
> #2  0x27BBA6F in __open_nocancel
> #3  0x227233F in __mpp_io_mod_MOD_mpp_read_compressed_r2d at
> mpp_read_compressed.h:39 (discriminator 17)
> #4  0x1A4EF23 in __fms_io_mod_MOD_read_compressed_2d at fms_io.F90:5173
> (discriminator 54)
> #5  0x1A4F75F in __fms_io_mod_MOD_read_compressed_1d at fms_io.F90:5131
> (discriminator 40)
> #6  0x7A091A in __ice_bergs_io_MOD_read_restart_bergs at
> icebergs_io.F90:801
> #7  0x17145B1 in __ice_bergs_MOD_icebergs_init at icebergs.F90:117
> #8  0x9F4E7A in __ice_model_mod_MOD_ice_model_init at ice_model.F90:2357
> (discriminator 16)
> #9  0xC0BA7D in coupler_init at coupler_main.F90:1565
> #10  0xBFF5AF in coupler_main at coupler_main.F90:524





--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540
